### PR TITLE
Set up Python packaging

### PR DESCRIPTION
**Pull request by akx**
Sibling of https://github.com/Stability-AI/stablediffusion/pull/269 but for the new fancy repo (and congrats on shipping)!

This makes it possible to build a standard Python `.whl` from the repo and use it instead of having to e.g. clone the entire repository.

## Features

* Adds `__version__` to `sgm/` (copying 0.0.1 from `setup.py`)
* Sets up packaging using `hatch` (removing the defunct `setup.py`)
  * `configs/` gets packaged as `sgm/configs` when using a packaged version
* Adds `sgm.get_configs_path()` to make it easy for downstream users to find the configs path

## Caveats

* Unlike [#269](https://github.com/Stability-AI/stablediffusion/pull/269), I **haven't** tested this with a downstream package (because I can't summon weights from thin air 😁)
* Requirements aren't yet handled here (because the current `requirements*` files are a bit messy), but I would recommend an approach where inference and training requirements are strictly separated, and training reqs would be installed with [optional requirements](https://hatch.pypa.io/latest/config/dependency/#features).

The package seems to be installable and the configs are correctly shipped:

```
$ docker run -it -v (pwd):/a:ro python:3.11 bash
root@a8a617f480ff:/# pip install /a/dist/sgm-0.0.1-py3-none-any.whl
Processing /a/dist/sgm-0.0.1-py3-none-any.whl
Successfully installed sgm-0.0.1
root@a8a617f480ff:/# python
>>> import sgm
...
ModuleNotFoundError: No module named 'torchdata'
>>>
root@a8a617f480ff:/# ls -la /usr/local/lib/python3.11/site-packages/sgm/configs/
total 16
drwxr-xr-x 4 root root 4096 Jun 27 08:53 .
drwxr-xr-x 7 root root 4096 Jun 27 08:53 ..
drwxr-xr-x 4 root root 4096 Jun 27 08:53 example_training
drwxr-xr-x 2 root root 4096 Jun 27 08:53 inference
```

### CODE REVIEW

**Comment by benjaminaubin** [comment]
Hello @akx , 
I am starting reviewing your PR

**Comment by akx** [comment]
@benjaminaubin Cool - let me know if you have any questions.

**Review by benjaminaubin — CHANGES_REQUESTED** [review]
@akx could you
- add in the documentation a section `Packaging` with commands `pip install hatch` `hatch build .` and `pip3 install xxxx.whl`
- add `**.pyc` to gitignore
- split requirements in train / inference as suggested

**Comment by akx** [comment]
@benjaminaubin Thank you 🙌 

* Rebased
* Added `*.py[cod]` to .gitignore (and sorted the file 🧹)
* Added a section on packaging with a note that dependencies are not yet specified for the built package
* I'll take a look at the requirements in a subsequent PR, if that's okay? It will also change the general installation instructions (as it will become something like `pip install -e .[train]`).

**Comment by benjaminaubin** [comment]
Looks great to me. 
Agreed requirements split can be done in another PR

**Review by benjaminaubin — APPROVED** [review]

**Comment by akx** [comment]
@benjaminaubin Awesome, thanks! Can you take a look at #44? It's a requirement for being able to split requirements.

**Comment by tubylec8** [comment]
How to install it?

**Pull request merged**
