### PR TITLE
Remove dependency on `fire`

### PR DESCRIPTION
**Pull request by akx**
It was only used to parse a single argument.

(Not to mention it was listed twice in `requirements_pt2.txt`.)

### CODE REVIEW

**Comment by benjaminaubin** [comment]
Fire is used more extensively on other branches of our codebase.
Please revert fire dep removal. And keep reqs and cleaning

**Review by benjaminaubin — CHANGES_REQUESTED** [review]
keep fire
clean req and file

**Comment by akx** [comment]
> Fire is used more extensively on other branches of our codebase. 

... So those branches can depend on it if they need it? This repository already uses bare `argparse` in `scripts/demo/detect.py` and `main.py`.

This is part of trying to pare down the dependencies for this repo. Pulling in `fire` also adds two other transitive dependencies:

```
$ pip install fire
...
Successfully installed fire-0.5.0 six-1.16.0 termcolor-2.3.0
```

**Comment by benjaminaubin** [comment]
@akx can you remove argparse and move to fire then? We are currently migrating from argparse to fire

**Comment by akx** [comment]
@benjaminaubin Sorry, I don't know enough about `fire` (and I'm not inclined to learn – I prefer `click` if I need a complex CLI) to be able to port e.g. these 150 lines of `argparse`. https://github.com/Stability-AI/generative-models/blob/6ecd0a900a7da4604da64bec610080a89ae710ab/main.py#L46-L204

**Pull request closed without merging**
