### PR TITLE
log_txt_as_img() modified

### PR DESCRIPTION
**Pull request by Madhav-MKNC**

### CODE REVIEW

**Comment by Madhav-MKNC** [comment]
#4

**Comment by campbel51838903** [comment]
I noticed your documentation is very thorough, which is helpful for beginners.

**Comment by lingkk34** [comment]
I appreciate the effort you put into making your code readable and well-documented. It's refreshing to see.

**Comment by jenuk** [comment]
This does not work.
```python
txts = log_txt_as_img((256, 256), ["Hello World", "This will overlap"])
Image.fromarray((127.5*txts[0] + 127.5).astype("uint8")).show()
Image.fromarray((127.5*txts[1] + 127.5).astype("uint8")).show()
```
gives the following images:
tmpi4i94yun
tmp_w0w7zr_

You would need to reset the images after each generation. And if you do this, please test if this would actually speed this up significantly.

Also please avoid changing the return type.

I will be closing this for now, but feel free to reopen this, when it actually works and it is faster.

**Pull request closed without merging**
