### PR TITLE
add dev-container config file

### PR DESCRIPTION
**Pull request by balnarendrasapa**
Add dev-container to the project. Now, whenever somebody wants to contribute to this project, they don't have to install all the dependencies in their pc. Instead one can use vscode dev-container to create a container in docker and develop in that container and install all the dependencies in that environment so that after completion you can delete all the dependencies.

refer [this link](https://code.visualstudio.com/docs/devcontainers/containers) for more info

### CODE REVIEW

**Comment by palp** [comment]
Thanks for the contribution, however I've already been working on some devcontainer configs that include GPU support as well as setting up dependencies and defaults. I've created PR #104 for them, take a look and let me know if it works for you.

**Comment by balnarendrasapa** [comment]
I am actually working on a project related to large language models and I have come across this dev containers while working on this project. It required a lot of python dependencies and several other sql packages. I think these dependencies should be dealt with by dockerfile so that the dockerfile can also be used to deploy the project. I see that you are trying to install torch library in json file. I don't think that is good idea. It is best to write a dockerfile that installs all the needed dependencies in the dev container and link the json file to the dockerfile like this

image

I also faced another problem which is rebuilding the whole container everytime there is a need to install more dependencies. Rebuilding the container everytime would waste a lot of time. This happens when vscode detects changes in the json file. Instead what you guys can do is write a makefile in the root directory(we can simplify the commands by this makefile) see the below image(make dev-install runs this command). refer this [link](https://makefiletutorial.com/)

image

I have also noticed that you have added black formatter and pylance linter. I suggest you guys use flake8 as linter. I think adding them as githooks(pre-commit) would make the git commits more neat and error free. Instead of adding them as extensions vscode which would only highlight parts where there is an error. refer this [link ](https://pre-commit.com/) . git hooks for black and flake8 are available in github.

**Comment by palp** [comment]
> I think these dependencies should be dealt with by dockerfile so that the dockerfile can also be used to deploy the project. 

True, but

> I also faced another problem which is rebuilding the whole container everytime there is a need to install more dependencies. 

then you have this problem.

> I see that you are trying to install torch library in json file. 

So perhaps the better answer is to solve this with a custom devcontainer component (as one of the benefits of not using a dockerfile is the ability to use those components)

 
> I have also noticed that you have added black formatter and pylance linter. I suggest you guys use flake8 as linter. I think adding them as githooks(pre-commit) would make the git commits more neat and error free. Instead of adding them as extensions vscode which would only highlight parts where there is an error. refer this [link ](https://pre-commit.com/) . git hooks for black and flake8 are available in github.
> 
> I know that all these things kind of defeats the purpose of dev-container. But I would like to think that dev-containers are thin line between host os and dev os so that we know where everything related to the project is and what those are so that we can delete them later.

We use actions to reject PRs which I prefer to git hooks as it can prevent pushing code; and code should always be pushed so you don't lose it, even if it's not in a working state. But the setup of all this in the container could be improved.


Can we close this PR and move discussion to #104 ?

**Comment by balnarendrasapa** [comment]
okay....

**Pull request closed without merging**
